version: '3.2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/go/src/app
    depends_on:
      - db
  db:
    image: postgres
    environment:
        POSTGRES_USER: db
        POSTGRES_PASSWORD: db
    ports:
      - "5432:5432"