CREATE TABLE IF NOT EXISTS apps (
	id UUID PRIMARY KEY,
  	name VARCHAR(60) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS roles (
	id UUID PRIMARY KEY,
	app_id UUID NOT NULL REFERENCES apps ON DELETE CASCADE,
	name VARCHAR(60) NOT NULL,
	UNIQUE (app_id, name)
);

CREATE TABLE IF NOT EXISTS permissions (
	id UUID PRIMARY KEY,
	app_id UUID NOT NULL REFERENCES apps ON DELETE CASCADE,
	name VARCHAR(60) NOT NULL,
	UNIQUE (app_id, name)
);

CREATE TABLE IF NOT EXISTS role_permissions (
	id UUID PRIMARY KEY,
	permission_id UUID NOT NULL REFERENCES permissions ON DELETE CASCADE,
	role_id UUID NOT NULL REFERENCES roles ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS entity_roles (
	id UUID PRIMARY KEY,
	role_id UUID NOT NULL REFERENCES roles ON DELETE CASCADE,
	entity_id VARCHAR(60) NOT NULL,
	UNIQUE (entity_id, role_id)
);